# Taskfile pour le projet k8s
# Installation: brew install go-task/tap/go-task
# Utilisation: task --list
# Documentation: https://taskfile.dev

version: "3"

vars:
  ANSIBLE_DIR: ansible
  PROFILE: production
  REPORT_FILE: ansible-lint-report.json

tasks:
  default:
    desc: Afficher l'aide
    cmds:
      - task --list-all
    silent: true

  # Installation et configuration
  install:deps:
    desc: Installer toutes les dépendances
    cmds:
      - echo "Installation des dependances..."
      - 'echo "Outils requis: brew install ansible-lint yamllint markdownlint-cli2"'
      - ansible-galaxy install -r {{.ANSIBLE_DIR}}/requirements.yml
      - lefthook install
      - echo "Dependances installees"

  install:hooks:
    desc: Installer les git hooks avec lefthook
    cmds:
      - echo "Installation des git hooks..."
      - lefthook install
      - echo "Git hooks installes"

  install:galaxy:
    desc: Installer les collections et rôles Ansible
    cmds:
      - echo "Installation des collections Ansible..."
      - ansible-galaxy install -r {{.ANSIBLE_DIR}}/requirements.yml

  install:galaxy-update:
    desc: Mettre à jour les collections et rôles Ansible
    cmds:
      - echo "Mise a jour des collections..."
      - ansible-galaxy install -r {{.ANSIBLE_DIR}}/requirements.yml --force
      - echo "Collections mises a jour"

  # Linting
  lint:
    desc: Linter le projet Ansible
    cmds:
      - echo "Linting du projet..."
      - ansible-lint --profile={{.PROFILE}}

  lint:fix:
    desc: Linter et corriger automatiquement
    aliases: [format, fix]
    cmds:
      - echo "Linting avec auto-fix..."
      - ansible-lint --fix --profile={{.PROFILE}}

  lint:report:
    desc: Générer un rapport de linting (format CodeClimate)
    cmds:
      - echo "Generation du rapport..."
      - ansible-lint --format=codeclimate > {{.REPORT_FILE}}
      - echo "Rapport genere → {{.REPORT_FILE}}"

  lint:file:
    desc: "Linter un fichier spécifique (usage: task lint:file -- path/to/file.yml)"
    cmds:
      - ansible-lint --profile={{.PROFILE}} {{.CLI_ARGS}}

  lint:role:
    desc: "Linter un rôle spécifique (usage: task lint:role -- gitea)"
    cmds:
      - ansible-lint --profile={{.PROFILE}} {{.ANSIBLE_DIR}}/roles/{{.CLI_ARGS}}

  # Profils de linting
  lint:min:
    desc: Linter avec profil minimal
    cmds:
      - ansible-lint --profile=min

  lint:basic:
    desc: Linter avec profil basic
    cmds:
      - ansible-lint --profile=basic

  lint:moderate:
    desc: Linter avec profil moderate
    cmds:
      - ansible-lint --profile=moderate

  lint:safety:
    desc: Linter avec profil safety (recommandé)
    cmds:
      - ansible-lint --profile=safety

  lint:production:
    desc: Linter avec profil production (le plus strict)
    cmds:
      - ansible-lint --profile=production

  # Validation YAML
  yaml:lint:
    desc: Valider la syntaxe YAML
    cmds:
      - echo "Validation YAML..."
      - yamllint -c .yamllint --strict .

  yaml:fix:
    desc: Formater les fichiers YAML avec yamlfmt
    cmds:
      - yamlfmt -formatter retain_line_breaks=true .

  # Validation Markdown
  md:lint:
    desc: Valider la syntaxe Markdown
    cmds:
      - echo "Validation Markdown..."
      - markdownlint-cli2 "**/*.md" "#node_modules" "#venv" "#.cache"

  md:lint-fix:
    desc: Corriger automatiquement les fichiers Markdown
    cmds:
      - echo "Correction Markdown..."
      - markdownlint-cli2 --fix "**/*.md" "#node_modules" "#venv" "#.cache"

  # Vérification syntaxe Ansible
  syntax:check:
    desc: Vérifier la syntaxe des playbooks
    cmds:
      - for: {var: PLAYBOOKS, split: "\n"}
        cmd: ansible-playbook --syntax-check {{.ITEM}}
    vars:
      PLAYBOOKS:
        sh: find {{.ANSIBLE_DIR}}/playbooks -name "*.yml" -type f 2>/dev/null || echo ""

  syntax:check-file:
    desc: Vérifier la syntaxe d'un playbook spécifique
    cmds:
      - ansible-playbook --syntax-check {{.CLI_ARGS}}

  # Checks combinés
  check:
    desc: Lancer tous les checks (lint + yamllint + mdlint)
    deps:
      - lint
      - yaml:lint
      - md:lint

  check:quick:
    desc: Check rapide (lint seulement)
    deps:
      - lint

  # Git hooks
  hooks:test:
    desc: Tester les hooks pre-commit sur tous les fichiers
    aliases: [test-hooks]
    cmds:
      - echo "Test des hooks pre-commit..."
      - lefthook run pre-commit --all-files

  hooks:skip:
    desc: Exemple pour skip les hooks (info seulement)
    cmds:
      - 'echo "Pour bypasser les hooks:"'
      - echo "  LEFTHOOK=0 git commit -m 'message'"
      - echo "  LEFTHOOK_EXCLUDE=ansible-lint git commit -m 'message'"
    silent: true

  # Nettoyage
  clean:
    desc: Nettoyer les fichiers temporaires
    cmds:
      - echo "Nettoyage..."
      - find . -type f -name '*.retry' -delete
      - find . -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name '.pytest_cache' -exec rm -rf {} + 2>/dev/null || true
      - rm -f {{.REPORT_FILE}}
      - echo "Nettoyage termine"

  clean:cache:
    desc: Nettoyer le cache ansible-lint
    cmds:
      - rm -rf .cache/
      - echo "Cache nettoye"

  # CI/CD
  ci:
    desc: Commande CI complète
    deps:
      - install:deps
    cmds:
      - task: check
    requires:
      vars: []

  ci:fast:
    desc: CI rapide (sans install)
    cmds:
      - task: check

  # Debug et info
  info:
    desc: Afficher les informations sur l'environnement
    cmds:
      - 'echo "Informations environnement:"'
      - echo "  ansible-lint → $(ansible-lint --version | head -1)"
      - echo "  yamllint → $(yamllint --version 2>&1 || echo 'non installe')"
      - echo "  markdownlint-cli2 → $(markdownlint-cli2 --version 2>&1 || echo 'non installe')"
      - echo "  lefthook → $(lefthook version)"
      - echo "  ansible → $(ansible --version | head -1)"
      - echo "  task → $(task --version)"
    silent: true

  info:rules:
    desc: Lister toutes les règles ansible-lint disponibles
    cmds:
      - ansible-lint -L

  info:rule:
    desc: "Afficher les détails d'une règle (usage: task info:rule -- var-naming)"
    cmds:
      - ansible-lint -T {{.CLI_ARGS}}

  # Cluster k3d (local)
  k3d:stop:
    desc: "Arreter le cluster k3d local"
    cmds:
      - k3d cluster stop atlas-local
      - echo "✓ Cluster k3d 'atlas-local' arrete"

  k3d:delete:
    desc: "Supprimer le cluster k3d local"
    prompt: "Supprimer le cluster atlas-local ? Toutes les donnees seront perdues."
    cmds:
      - k3d cluster delete atlas-local
      - echo "✓ Cluster k3d 'atlas-local' supprime"

  k3d:status:
    desc: "Afficher le statut du cluster k3d local"
    cmds:
      - k3d cluster list

  # Déploiement avec résolution de dépendances
  deploy:local:
    desc: "Deployer en LOCAL (usage: task deploy:local -- mattermost)"
    cmds:
      - task: _ensure-k3d
      - task: _deploy
        vars: {ENV: local}

  deploy:staging:
    desc: "Deployer en STAGING (usage: task deploy:staging -- mattermost)"
    cmds:
      - task: _deploy
        vars: {ENV: staging}

  deploy:production:
    desc: "Deployer en PRODUCTION (usage: task deploy:production -- mattermost)"
    cmds:
      - task: _deploy
        vars: {ENV: production}

  deploy:list:
    desc: "Lister les composants deployables"
    cmds:
      - 'echo "Composants disponibles:" && grep -E "^\s{2}\w+:$" {{.ANSIBLE_DIR}}/vars/dependency_graph.yml | sed "s/://;s/^  /  - /"'
    silent: true

  deploy:deps:
    desc: "Afficher les dependances d'un composant (usage: task deploy:deps -- mattermost)"
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - ansible-playbook playbooks/deploy.yml -e target={{.CLI_ARGS}} --check
    preconditions:
      - sh: "[ -n '{{.CLI_ARGS}}' ]"
        msg: "Specifier un composant. Usage: task deploy:deps -- mattermost"

  # Infrastructure (phases 1+2)
  infra:local:
    desc: "Demarrer l'infrastructure locale (k3d)"
    cmds:
      - task: _ensure-k3d

  infra:staging:
    desc: "Deployer l'infra staging (phases 1+2: preparation + K3s + composants)"
    cmds:
      - task: _infra
        vars: {ENV: staging}

  infra:production:
    desc: "Deployer l'infra production (phases 1+2: preparation + K3s + composants)"
    cmds:
      - task: _infra
        vars: {ENV: production}

  # Reset cluster
  reset:local:
    desc: "Supprimer le cluster k3d local"
    prompt: "Supprimer le cluster atlas-local ? Toutes les donnees seront perdues."
    cmds:
      - task: k3d:delete

  reset:staging:
    desc: "Reset complet du cluster staging (desinstalle K3s)"
    prompt: "Reset complet du cluster staging ? Toutes les donnees seront perdues."
    cmds:
      - task: _ensure-env
        vars: {ENV: staging}
      - ./scripts/reset-cluster.sh staging

  reset:production:
    desc: "Reset complet du cluster production (desinstalle K3s)"
    prompt: "Reset complet du cluster PRODUCTION ? TOUTES les donnees seront DEFINITIVEMENT perdues."
    cmds:
      - task: _ensure-env
        vars: {ENV: production}
      - ./scripts/reset-cluster.sh production

  # Taches internes
  _ensure-k3d:
    internal: true
    desc: "Verifier et demarrer k3d si necessaire"
    cmds:
      - ./scripts/ensure-k3d.sh

  _ensure-env:
    internal: true
    desc: "Generer le fichier .env s'il n'existe pas"
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - |
        if [ ! -f ".env.{{.ENV}}" ]; then
          echo "📝 Generating .env.{{.ENV}}..."
          ./generate-env.sh {{.ENV}}
        else
          echo "✓ .env.{{.ENV}} already exists"
        fi
    silent: true

  _deploy:
    internal: true
    desc: "Deployer un composant (usage interne)"
    cmds:
      - task: _ensure-env
        vars: {ENV: "{{.ENV}}"}
      - ./scripts/ansible-run.sh {{.ENV}} -i inventories/{{.ENV}}/ playbooks/deploy.yml -e target={{.CLI_ARGS}}
    preconditions:
      - sh: "[ -n '{{.CLI_ARGS}}' ]"
        msg: "Specifier un composant. Usage: task deploy:{{.ENV}} -- mattermost"

  _infra:
    internal: true
    desc: "Deployer l'infrastructure (phases 1+2)"
    cmds:
      - task: _ensure-env
        vars: {ENV: "{{.ENV}}"}
      - ./scripts/ansible-run.sh {{.ENV}} -i inventories/{{.ENV}}/ playbooks/phase-01-preparation.yml
      - ./scripts/ansible-run.sh {{.ENV}} -i inventories/{{.ENV}}/ playbooks/phase-02-k3s-core.yml
