#!/usr/bin/env bash
# generate-env.sh — Generate a .env file with cryptographically random secrets
# Usage: ./generate-env.sh [--force]
#
# Generates all required secrets and writes ansible/.env
# Will NOT overwrite an existing .env unless --force is passed.
# Values you must fill in manually are marked with FIXME.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

# ─── Pre-flight checks ───────────────────────────────────────────────────────

if [[ -f "$ENV_FILE" ]] && [[ "${1:-}" != "--force" ]]; then
  echo "ERROR: ${ENV_FILE} already exists."
  echo "  Use --force to overwrite, or edit the existing file."
  exit 1
fi

command -v openssl >/dev/null 2>&1 || { echo "ERROR: openssl is required"; exit 1; }

# ─── Load external configs ──────────────────────────────────────────────────

SMTP_ENV="${SCRIPT_DIR}/.smtp.env"
if [[ -f "$SMTP_ENV" ]]; then
  # shellcheck source=/dev/null
  source "$SMTP_ENV"
  echo "Loaded SMTP config from .smtp.env"
else
  echo "No .smtp.env found — SMTP will be empty in .env"
fi

# ─── Secret generators ───────────────────────────────────────────────────────

hex32()   { openssl rand -hex 32; }
b64_24()  { openssl rand -base64 24 | tr -d '\n'; }
b64_32()  { openssl rand -base64 32 | tr -d '\n'; }
b64_16()  { openssl rand -base64 16 | tr -d '\n'; }
alphanum() { openssl rand -base64 "${1:-24}" | tr -dc 'A-Za-z0-9' | head -c "${1:-24}"; }

# ─── Generate secrets ─────────────────────────────────────────────────────────

K3S_TOKEN="$(hex32)"
POSTGRES_SUPERUSER_PASSWORD="$(b64_24)"
POSTGRES_REPLICATION_PASSWORD="$(b64_24)"
REDIS_PASSWORD="$(b64_24)"
LONGHORN_CRYPTO_KEY="$(b64_32)"
ETCD_ENCRYPTION_KEY="$(b64_32)"

# Service admin passwords
KEYCLOAK_ADMIN_PASSWORD="$(alphanum 24)"
MATTERMOST_ADMIN_PASSWORD="$(alphanum 24)"
NEXTCLOUD_ADMIN_PASSWORD="$(alphanum 24)"
GITEA_ADMIN_PASSWORD="$(alphanum 24)"
ARGOCD_ADMIN_PASSWORD="$(alphanum 24)"
GRAFANA_ADMIN_PASSWORD="$(alphanum 24)"

# Per-service DB passwords
VAULT_DB_PASSWORD="$(b64_24)"
KEYCLOAK_DB_PASSWORD="$(b64_24)"
MATTERMOST_DB_PASSWORD="$(b64_24)"
NEXTCLOUD_DB_PASSWORD="$(b64_24)"
GITEA_DB_PASSWORD="$(b64_24)"
REDCAP_DB_PASSWORD="$(b64_24)"
FLIPT_DB_PASSWORD="$(b64_24)"

# Service secrets
REDCAP_SALT="$(b64_32)"
SEAWEEDFS_S3_ACCESS_KEY="$(alphanum 20)"
SEAWEEDFS_S3_SECRET_KEY="$(b64_32)"
ONLYOFFICE_JWT_SECRET="$(b64_32)"

# ─── Write .env ───────────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<ENVFILE
# ATLAS Platform - Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Generated by: generate-env.sh
#
# FIXME lines require manual configuration before deployment.

# =============================================================================
# REQUIRED - All Environments
# =============================================================================

export K3S_TOKEN="${K3S_TOKEN}"
export POSTGRES_SUPERUSER_PASSWORD="${POSTGRES_SUPERUSER_PASSWORD}"
export POSTGRES_REPLICATION_PASSWORD="${POSTGRES_REPLICATION_PASSWORD}"
export REDIS_PASSWORD="${REDIS_PASSWORD}"

# =============================================================================
# REQUIRED - Production Only (FIXME: fill in your values)
# =============================================================================

export PROD_DOMAIN="FIXME.example.com"       # FIXME: your production domain
export ADMIN_IP="FIXME/32"                    # FIXME: admin CIDR for K3s API
export LETSENCRYPT_EMAIL="FIXME@example.com"  # FIXME: email for TLS certs

# Production server IPs (FIXME: set your server addresses)
export PROD_MASTER_HOST="FIXME"
export PROD_WORKER1_HOST="FIXME"
export PROD_WORKER2_HOST="FIXME"
export PROD_WORKER3_HOST="FIXME"
export PROD_SSH_KEY="~/.ssh/production_key"

# =============================================================================
# ENCRYPTION KEYS
# =============================================================================

export LONGHORN_CRYPTO_KEY="${LONGHORN_CRYPTO_KEY}"
export ETCD_ENCRYPTION_KEY="${ETCD_ENCRYPTION_KEY}"

# =============================================================================
# VAULT (leave empty until after vault init, then paste the output)
# =============================================================================

export VAULT_ROOT_TOKEN=""
export VAULT_UNSEAL_KEYS='[]'

# =============================================================================
# SERVICE ADMIN PASSWORDS
# =============================================================================

export KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD}"
export MATTERMOST_ADMIN_PASSWORD="${MATTERMOST_ADMIN_PASSWORD}"
export NEXTCLOUD_ADMIN_PASSWORD="${NEXTCLOUD_ADMIN_PASSWORD}"
export GITEA_ADMIN_PASSWORD="${GITEA_ADMIN_PASSWORD}"
export ARGOCD_ADMIN_PASSWORD="${ARGOCD_ADMIN_PASSWORD}"
export GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD}"

# =============================================================================
# PER-SERVICE DATABASE PASSWORDS
# =============================================================================

export VAULT_DB_PASSWORD="${VAULT_DB_PASSWORD}"
export KEYCLOAK_DB_PASSWORD="${KEYCLOAK_DB_PASSWORD}"
export MATTERMOST_DB_PASSWORD="${MATTERMOST_DB_PASSWORD}"
export NEXTCLOUD_DB_PASSWORD="${NEXTCLOUD_DB_PASSWORD}"
export GITEA_DB_PASSWORD="${GITEA_DB_PASSWORD}"
export REDCAP_DB_PASSWORD="${REDCAP_DB_PASSWORD}"
export FLIPT_DB_PASSWORD="${FLIPT_DB_PASSWORD}"

# =============================================================================
# SERVICE SECRETS
# =============================================================================

export REDCAP_SALT="${REDCAP_SALT}"
export SEAWEEDFS_S3_ACCESS_KEY="${SEAWEEDFS_S3_ACCESS_KEY}"
export SEAWEEDFS_S3_SECRET_KEY="${SEAWEEDFS_S3_SECRET_KEY}"
export ONLYOFFICE_JWT_SECRET="${ONLYOFFICE_JWT_SECRET}"

# =============================================================================
# SMTP (Email delivery via Brevo or other provider)
# =============================================================================
# To configure: edit .smtp.env then re-run generate-env.sh

export SMTP_HOST="${SMTP_HOST:-}"
export SMTP_PORT="${SMTP_PORT:-587}"
export SMTP_USER="${SMTP_USER:-}"
export SMTP_PASSWORD="${SMTP_PASSWORD:-}"
export SMTP_FROM="${SMTP_FROM:-}"

# =============================================================================
# OPTIONAL - Vault Auto-Unseal
# =============================================================================

# export VAULT_AUTO_UNSEAL_ENABLED="true"
# export VAULT_AUTO_UNSEAL_TYPE="awskms"
# export AWS_REGION="eu-west-1"
# export VAULT_AWSKMS_KEY_ID="FIXME"

# =============================================================================
# OPTIONAL - Off-Site Backup
# =============================================================================

# export BACKUP_S3_ENDPOINT="s3.amazonaws.com"
# export BACKUP_S3_BUCKET="atlas-backups"
# export BACKUP_S3_REGION="eu-west-1"
# export BACKUP_S3_ACCESS_KEY="FIXME"
# export BACKUP_S3_SECRET_KEY="FIXME"
# export BACKUP_ENCRYPTION_KEY="$(b64_32)"
ENVFILE

# ─── Permissions ──────────────────────────────────────────────────────────────

chmod 600 "$ENV_FILE"

# ─── Summary ─────────────────────────────────────────────────────────────────

echo ""
echo "Generated: ${ENV_FILE}"
echo "Permissions: 600 (owner read/write only)"
echo ""
echo "Secrets generated:"
echo "  - 1  K3s cluster token (hex, 256-bit)"
echo "  - 3  Database passwords (PostgreSQL superuser, replication, Redis)"
echo "  - 7  Per-service DB passwords (Vault, Keycloak, Mattermost, Nextcloud, Gitea, REDCap, Flipt)"
echo "  - 6  Admin passwords (Keycloak, Mattermost, Nextcloud, Gitea, ArgoCD, Grafana)"
echo "  - 2  Encryption keys (Longhorn LUKS, etcd at-rest)"
echo "  - 3  Service secrets (REDCap salt, SeaweedFS S3, OnlyOffice JWT)"
echo ""
if [[ -f "$SMTP_ENV" ]]; then
  echo "  - SMTP config imported from .smtp.env"
else
  echo "  - SMTP not configured (create .smtp.env and re-run, or edit .env manually)"
fi
echo ""
echo "FIXME items to configure manually:"
FIXME_COUNT=$(grep -c "FIXME" "$ENV_FILE" || true)
if [[ "$FIXME_COUNT" -gt 0 ]]; then
  echo "  - ${FIXME_COUNT} lines need your attention (search for FIXME)"
else
  echo "  - None! All values are set."
fi
echo ""
echo "Next steps:"
echo "  1. Edit .env and replace all FIXME values"
echo "  2. source ansible/.env"
echo "  3. ansible-playbook ansible/playbooks/phase-00-bootstrap.yml"
echo ""
echo "IMPORTANT: Back up this file securely. These secrets cannot be recovered."
